
target_reliability: 1.
unit_wise_target_reliability: [1., 1., 1., 1., 1., 1.]
deus: 
  activity_type: 'dsc'

notion_of_feasibility: 'positive'
ku_approximation: 'box'
vol_scale: 0.05

ns:
  n_live: 100 # 100
  final_sample_live: 15000 # 6000  
  n_replacements: 50 
  n_iter: 15000 
  f0: 0.1
  alpha: 0.2
  prior: Uniform
  rejector: suob-ellipsoid
  log_evidence_estimation: True

bo:
  bounds: 
    max: 1
    min: 0
  num_initial_points: 3
  num_iterations: 7 # subsequent to initial samples
  acq: 'ei'