penalty_method_coupler:
  n_starts: 4
  n_iterates: 7
  mu_increment: 2.5
  mu_og: 2.5
  ftol0: 0.001
  ftol_increment: 0.01
  augmented_grad_tol: 0.01
  augmented_constr_tol: 0.01
  ftol_min: 0.00001
  augmented_obj_tol: 0.001


evaluation_mode: 
  forward: ray #mp-ms
  backward: jax-pmap #serial 


forward_coupling_solver: general_constrained_nlp
backward_coupling_solver: box_constrained_nlp
forward_general_constraints: True
ost_process_solver: 
  lower_level: box_constrained_nlp
  upper_level: general_constrained_nlp

forward_coupling:
  max_solution_time: 1. # if forward solution > 1s then raise warning
  parallelised: True
  n_starts: 4
  casadi_ipopt_options:
    maxiter: 1000
    verbose: False
    tol: 1e-6
    options:
      verbose: 0
      maxiter: 1000
      disp: False
  jax_opt_options:
    n_starts: 4
    n_iterates: 7
    mu_increment: 2.5
    mu_og: 2.5
    ftol0: 0.001
    ftol_increment: 0.01
    augmented_grad_tol: 0.01
    augmented_constr_tol: 0.01
    ftol_min: 0.00001
    augmented_obj_tol: 0.001

standardised: False #  true


# TODO: check standardisation is working properly in the backward pass
backward_coupling:
  tightening: False
  n_starts:   4
  jax_opt_options:
    error_tol: 1e-6
    ftol0: 0.001
    ftol_increment: 0.01
    augmented_grad_tol: 0.01
    augmented_constr_tol: 0.01
    ftol_min: 0.00001
    augmented_obj_tol: 0.001
  

post:
  n_starts:   10
  jax_opt_options:
    error_tol: 1e-6
    ftol0: 0.001
    ftol_increment: 0.01
    augmented_grad_tol: 0.01
    augmented_constr_tol: 0.01
    ftol_min: 0.00001
    augmented_obj_tol: 0.001


post_upper_level:
  max_solution_time: 1. 
  parallelised: False
  n_starts: 16
  casadi_ipopt_options:
    maxiter: 500
    verbose: False
    tol: 1e-6
    options:
      verbose: 0
      maxiter: 1000
      disp: False
  jax_opt_options:
    n_starts: 4
    n_iterates: 7
    mu_increment: 2.5
    mu_og: 2.5
    ftol0: 0.001
    ftol_increment: 0.01
    augmented_grad_tol: 0.01
    augmented_constr_tol: 0.01
    ftol_min: 0.00001
    augmented_obj_tol: 0.001