

reconstruct: 
  - True


post_process: 
  - True


relaxation_b_index_bounds: [0.0, 1.0]

post_process_solver:
 lower_level: 'post_process_lower_level'
 upper_level: 'post_process_upper_level'
 relaxation_a: post_process_upper_level
 relaxation_b: post_process_lower_level

post_process_sampler: False # if True, use sampling scheme, if False use local SIP scheme

post_process_decision_indices: [10, 11]

plot_reconstruction: nominal_map # probability_map #


reconstruction_scheme: uniform #sobol
